
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - seceretreload.secretsreload.test
  resources:
  - sqssecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - seceretreload.secretsreload.test
  resources:
  - sqssecrets/status
  verbs:
  - get
  - patch
  - update
