# permissions for end users to view sqssecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sqssecrets-viewer-role
rules:
- apiGroups:
  - seceretreload.secretsreload.test
  resources:
  - sqssecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - seceretreload.secretsreload.test
  resources:
  - sqssecrets/status
  verbs:
  - get
